### ISSUE TITLE
4 second game freeze/lag every 10-15 seconds

### ISSUE THREAD

**Issue by jakkarth** [jrossignol/ContractPack-FieldResearch#1]
I've got 6 contract packs installed plus contract configurator via CKAN, and they all run perfectly with no performance problems. As soon as I add Contract Pack: Field Research (1.0.1 since that's what ckan has apparently) I start getting massive lag spikes. The game will run smoothly for about 10 seconds, then freeze for 5, then back to running smoothly for 10 more seconds, then freeze for 5. Sound continues to play, but controls are completely unresponsive (including hitting escape to bring up the revert menu) and there are no graphical updates. Nothing is visible in the log during flight when this happens. I'm happy to provide my full log, screenshots, whatever you need. This mod looks awesome and I'd love to use it!

I apologise if this was fixed in 1.0.2. If so, I'll either wait for it to be updated in CKAN or install it by hand the old fashioned way. Thanks for taking the time to look at this, and for making what I hope will be a fun mod :)

**Comment by jrossignol** [comment]
Already tracked under https://github.com/jrossignol/ContractConfigurator/issues/225
