### ISSUE TITLE
Do not offer Station Science Experiments

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractPack-FieldResearch#11]
From Mermel on [the forums](http://forum.kerbalspaceprogram.com/threads/123892-1-0-4-Contract-Pack-Field-Research-v1-1-1-2015-09-04?p=2212829&viewfull=1#post2212829):

> I want to speak in favor of removing the station science experiments from field research.
> 
> 1.) Station Science comes with included contracts for the experiments.
> 2.) The Station Science experiments are even more hefty than you realize, going up to 75t (I think) of mass required to be towed to the target location.
> 
> Generally all Field Research Contracts including any Station Science experiment is a direct no go. The payoff offered by your contracts for performing those experiments is at least an order of magnitude below what is required to make them interesting. Getting a pretty high 5 digit payoff to tow at least 15t of mass to the next planet is not even beginning to cover the costs.
> Lately it led me to start ignoring my Field Research contracts alltogether as they often include those parts. 
> So, please take them out and let them be handled by the contracts delivered together with the parts.

**Comment by jrossignol** [comment]
Probably worth considering, especially because of point 1 above.

**Comment by TheDude044** [comment]
I think, DMagic is OK, but Station Science should be removed. Just imagine the task if playing with outer planets mod, bring 75t to Tekto :-)

**Comment by jrossignol** [comment]
Done.
