### ISSUE TITLE
Oversize  Signals Intelligence Satellite

### ISSUE THREAD

**Issue by Alarcarr** [jrossignol/ContractPack-FieldResearch#18]
This antena/science experiment is stated to be an 1T antenna but I lost connection to KSC as soon as my Command pod /Remote Guidance unit antenna was out of range

So i guess that antenna part is not working at all. I extended it obviously.

Two screenshots to show it more clearly where u can see I have power .
![screenshot35](https://cloud.githubusercontent.com/assets/10220609/19901826/bc421302-a068-11e6-958c-270134c54318.png)
![screenshot33](https://cloud.githubusercontent.com/assets/10220609/19901832/c351aa18-a068-11e6-927e-6b722f0c4a44.png)

**Comment by jrossignol** [comment]
I think you're in the wrong place, this is the GitHub for the field research contact pack - nothing to do with antennas.
