### ISSUE TITLE
Breaking Ground Surface Features

### ISSUE THREAD

**Issue by Lathari** [jrossignol/ContractPack-FieldResearch#26]
Sometimes "help scientist" contracts require scan arm scanning but no features near the waypoint.

**Comment by jrossignol** [comment]
I spent some time looking into a way to spawn the waypoint by a surface feature, but no luck.  Their positions aren't determined until they are visible, and simulating it requires diving way too far into the madness that is the Planetary Quad System.

So I'll just disable these experiments from the Scientist contract instead.
