### ISSUE TITLE
Stuttering.

### ISSUE THREAD

**Issue by dphrag** [jrossignol/ContractPack-FieldResearch#5]
This took me awhile to ensure it was this mod.

However, anytime I have an active Field Research contract, and then am in my ship or launch or whatever, there is definite stuttering. Debug window shows a pile of:

[Warning]: ContractConfigurator.ContractPreLoader: Contract attribute took too long (0.1235657 seconds) to generate: FS_HardScience[scienceSubjectsTemp1]

If I cancel those contracts, the stuttering goes away. Very strange!

Let me know if you have any questions or want some confirmation.

**Comment by jrossignol** [comment]
Thanks for the bug report.  I'm aware of the issue and will be looking into
it soon.

**Comment by jrossignol** [comment]
Raised [#251](https://github.com/jrossignol/ContractConfigurator/issues/251) against Contract Configurator.  Closing this issue.
